### ISSUE TITLE
`isBefore` and `isAfter` config values should contain itself when comparing

### ISSUE THREAD

**Issue by Asim-Tahir** [horprogs/just-validate-plugin-date#1]
## Problem 😵‍💫
```js
import JustValidatePluginDate from "just-validate-plugin-date";

validation.addField("input[type=date][name=start_date]", [
  {
    plugin: JustValidatePluginDate(() => ({
      format: "yyyy-mm-dd",
      isBefore: "2022-06-08", // or new Date(2022, 5, 8)
      isAfter: "2022-06-02" // or new Date(2022, 5, 2)
    })),
    errorMessage: "Date should be between 2022-06-02 and 2022-06-08",
  },
]);
```

Validation fails when `input[type="date"][name="start_date"]` value is `2022-06-08`. Likewise, when the input value is set to `2022-06-02` validation fails. Both exclude itself when compared to the input value.

## Expectation 💭

When the input value is equal to `isBefore` or `isAfter` should validate with no fails.

## Temporary Solution 🤞🏻

Add one day to `isBefore` and subtract one day to `isAfter`.

```js
import JustValidatePluginDate from "just-validate-plugin-date";

const isBefore = new Date(2022, 5, 8);
isBefore.setDate(isBefore.getDate() + 1);
const isAfter = new Date(2022, 5, 2);
isAfter.setDate(isAfter.getDate() - 1);

validation.addField("input[type=date][name=start_date]", [
  {
    plugin: JustValidatePluginDate(() => ({
      format: "yyyy-mm-dd",
      isBefore,
      isAfter
    })),
    errorMessage: "Date should be between 2022-06-02 and 2022-06-08",
  },
]);

```

**Comment by horprogs** [comment]
Thanks for the reporting. 

I decided to keep the `isAfter` and `isBefore` as it is, but I added the new validators: `isBeforeOrEqual`, `isAfterOrEqual` and just in case if needed to compare just for the same day: `isEqual`

Released `1.2.0` version
