### ISSUE TITLE
Validate two date fields with the same date

### ISSUE THREAD

**Issue by albinlang** [horprogs/just-validate-plugin-date#2]
Hi,

I'm having problem validating an "end_date" being after my "start_date" using isAfter.

I need to be able to pick the same date in my inputs since an event can be running for only one day. 

Not sure if this is by design or a bug. Is there a way to allow picking the same date for cases like this?

**Comment by horprogs** [comment]
Hi, could you please check https://github.com/horprogs/just-validate-plugin-date/issues/1
